# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('checkin_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VenueSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('near', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='venue',
            name='search_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wheretoeat.VenueSearch'),
        ),
    ]
