# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoeat', '0003_chat_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null='True'),
        ),
    ]
