# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoeat', '0017_userprofile_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
