# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-09 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wheretoeat', '0019_auto_20170809_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created_en',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='created_tr',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='from_user_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='from_user_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='message_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='message_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='to_user_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='to_user_tr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='display',
            name='displayed_by_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displayed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='display',
            name='displayed_by_tr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displayed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='display',
            name='displayed_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displayed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='display',
            name='displayed_tr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='displayed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_joined_en',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_joined_tr',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_en',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_tr',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name_tr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_en',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_tr',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name_tr',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_en',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_tr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username_tr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='checkin_count_en',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='checkin_count_tr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone_number_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='phone_number_tr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='search_id_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wheretoeat.VenueSearch'),
        ),
        migrations.AddField(
            model_name='venue',
            name='search_id_tr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wheretoeat.VenueSearch'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_id_en',
            field=models.CharField(default='something', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_id_tr',
            field=models.CharField(default='something', max_length=200, null=True),
        ),
    ]
