# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 08:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoeat', '0021_auto_20170811_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
