# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheretoeat', '0022_auto_20170816_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
